---
# tasks file for aws-configure
- name: Set aws_access_key_id
  ansible.builtin.shell:
    cmd: "aws configure set aws_access_key_id {{aws_access_key_id}}"
- name: Set aws_secret_access_key
  ansible.builtin.shell:
    cmd: "aws configure set aws_secret_access_key {{aws_secret_access_key}}"
- name: Set default.region
  ansible.builtin.shell:
    cmd: "aws configure set default.region {{default_region}}"
